# REF: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#creating-a-deployment

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: Reviews-Deployment
spec:
  selector:
    matchLabels:
      app: reviews
  replicas: 
  template:   # create pods using pod definition in this template
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /src
          name: reviews-src
        command: ["/bin/sh", "-c"]
        args: ["cd /src/Frontend/ && cp ./dist/* /usr/share/nginx/html"]

      - name: api
        image: golang
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /src
          name: reviews-src
        command: ["/bin/sh", "-c"]
        args: ["cd /src/Backend/ && go build -o server && ./server"]

    volumes:
    - name: reviews-src
      gitRepo:
        repository: "https://github.com/salvacorts/reviews-web-parser.git"
        revision: "2c808918dbd2c76eef3558e194aa7dee26525258"
