FROM golang

# Copy gcp credentials json
ENV GOOGLE_APPLICATION_CREDENTIALS /app/gpd-creds.json

# Create directory
RUN mkdir /app
ADD ./creds.json $GOOGLE_APPLICATION_CREDENTIALS
ADD . /app/

# Move to directory and build source
WORKDIR /app/
RUN go get cloud.google.com/go/language/apiv1
RUN go get github.com/PuerkitoBio/goquery
RUN go get github.com/google/goterm/term
RUN go get github.com/gorilla/mux
RUN go build -o server .

# Execute server main
CMD ["/app/server"]